-- Function to create agent profile when 'agent' role is assigned
CREATE OR REPLACE FUNCTION public.create_agent_on_role_assignment()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  profile_record RECORD;
BEGIN
  -- Only proceed if the role being assigned is 'agent'
  IF NEW.role = 'agent' THEN
    -- Get profile data for the user
    SELECT full_name, phone, avatar_url INTO profile_record
    FROM public.profiles
    WHERE id = NEW.user_id;
    
    -- Insert into delivery_agents (agent_code will be auto-generated by existing trigger)
    INSERT INTO public.delivery_agents (user_id, full_name, phone, avatar_url)
    VALUES (
      NEW.user_id,
      COALESCE(profile_record.full_name, 'Agent'),
      profile_record.phone,
      profile_record.avatar_url
    )
    ON CONFLICT (user_id) DO NOTHING;
  END IF;
  
  RETURN NEW;
END;
$$;

-- Create trigger on user_roles table
DROP TRIGGER IF EXISTS trigger_create_agent_on_role ON public.user_roles;
CREATE TRIGGER trigger_create_agent_on_role
  AFTER INSERT ON public.user_roles
  FOR EACH ROW
  WHEN (NEW.role = 'agent')
  EXECUTE FUNCTION public.create_agent_on_role_assignment();

-- Function to deactivate agent when 'agent' role is removed
CREATE OR REPLACE FUNCTION public.deactivate_agent_on_role_removal()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF OLD.role = 'agent' THEN
    UPDATE public.delivery_agents
    SET is_active = false
    WHERE user_id = OLD.user_id;
  END IF;
  RETURN OLD;
END;
$$;

-- Create trigger for role removal
DROP TRIGGER IF EXISTS trigger_deactivate_agent_on_role_removal ON public.user_roles;
CREATE TRIGGER trigger_deactivate_agent_on_role_removal
  AFTER DELETE ON public.user_roles
  FOR EACH ROW
  WHEN (OLD.role = 'agent')
  EXECUTE FUNCTION public.deactivate_agent_on_role_removal();

-- Backfill: Create delivery_agents for existing users with 'agent' role
INSERT INTO public.delivery_agents (user_id, full_name, phone, avatar_url)
SELECT 
  ur.user_id,
  COALESCE(p.full_name, 'Agent'),
  p.phone,
  p.avatar_url
FROM public.user_roles ur
LEFT JOIN public.profiles p ON p.id = ur.user_id
WHERE ur.role = 'agent'
  AND NOT EXISTS (
    SELECT 1 FROM public.delivery_agents da WHERE da.user_id = ur.user_id
  );